<?php
return array(
    'WEBSITE' =>  array(
        'website_name' => '天迅达项目后台',
        'website_url' => 'http://frame.com',
        'website_keyword' => '框架 后台 layui',
        'website_description' => '网站介绍',
    ),
    'SMS' =>  array(
        'sms_type' => 'zhutong',
        'sms_url' => 'http://www.api.zthysms.com/sendSms.do',
        'sms_key' => 'xeyhy',
        'sms_secret' => 'pTVuI7',
        'sms_sign' => 'aa',
    ),
    'APP' =>  array(
        'app_logo' => '',
        'app_name' => '3445',
        'app_version' => '5454',
        'app_intro' => '444',
    ),
    'PUSH' =>  array(
        'push_type' => 'ac',
        'push_key' => 'asc',
        'push_secret' => 'asc',
    ),
    'WXJSAPI' =>  array(
        'wxjsapi_appid' => 'ca',
        'wxjsapi_appsecret' => 's',
        'wxjsapi_mch_id' => 'cas',
        'wxjsapi_key' => 'casc',
    ),
    'WXAPP' =>  array(
        'wxapp_appid' => 'ascas',
        'wxapp_appsecret' => 'casc',
        'wxapp_mch_id' => 'ascas',
        'wxapp_key' => 'casc',
    ),
    'ALIH5' =>  array(
        'alih5_appid' => 'aaa',
        'alih5_public_key' => 'aa',
        'alih5_private_key' => 'aaa',
    ),
    'ALIAPP' =>  array(
        'aliapp_appid' => 'a',
        'aliapp_public_key' => 's',
        'aliapp_private_key' => 'c',
    ),
    'MENU_ICON' =>  array(
        '1' => 'rate',
        '2' => 'cellphone',
        '3' => 'vercode',
        '4' => 'upload-drag',
        '5' => 'auz',
        '6' => 'snowflake',
        '7' => 'senior',
        '8' => 'flag',
        '9' => 'theme',
        '10' => 'website',

        '11' => 'surprised',
        '12' => 'template-1',
        '13' => 'app',
        '14' => 'template',
        '15' => 'camera',
        '16' => 'diamond',
        '17' => 'fire',
        '18' => 'read',
        '19' => 'survey',
        '20' => 'simple',

        '21' => 'component',
        '22' => 'file-b',
        '23' => 'praise',
        '24' => 'release',
        '25' => 'chat',
        '26' => 'layouts',
        '27' => 'util',
        '28' => 'water',
        '29' => 'engine',
        '30' => 'chart',

        '31' => 'location',
        '32' => 'code-circle',
        '33' => 'carousel',
        '34' => 'set-sm',
        '35' => 'chart-screen',
        '36' => 'list',
        '37' => 'face-smile-fine',
        '38' => 'picture-fine',
        '39' => 'top',
        '40' => 'star',
    ),
);
